### 
POST http://localhost:8000/api/token/
Content-Type: application/json 

{"email":"user@user.com", "password":"user"}

### 
GET http://localhost:8000/image/hello/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA1MjI3NzY2LCJpYXQiOjE3MDUyMjc0NjYsImp0aSI6ImM3NzE0ODE5ZTY4NDRjNzNiN2Y1MGIxNjMwMjI1YWYyIiwidXNlcl9pZCI6MX0.XDcQl7_nLfoY81w2taFSN891E21SbrXPrSXKWlEkKp4


###
POST http://localhost:8000/image/combined/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA1MjI4MjkxLCJpYXQiOjE3MDUyMjc5OTEsImp0aSI6ImM4ZGRiZDBkYWRjYzQyM2FhZjQzNzNlNDMzNzNmOTE5IiwidXNlcl9pZCI6MX0.eDnxAG9GkQ13Ng6y8254qfLltYm6UamI_axzgvKtOkQ
