### 
POST http://localhost:8000/api/token/
Content-Type: application/json 

{"email":"user@user.com", "password":"user"}

### Combined api call
POST http://localhost:8000/image/combined/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA1MzE5MzIxLCJpYXQiOjE3MDUzMTkwMjEsImp0aSI6IjM3YzNlYzhmYzljMDQwN2ZiMzk3NzhiOWEyN2EyYWYwIiwidXNlcl9pZCI6MX0.67vk5j6rRPzKbWShVPImxNgp0lFIt4q3AReKykG8Q2w

{
    "image_url":"", 
    "face_url":""
}


### Face api call
POST http://localhost:8000/image/faceswap/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA1MzE5MzIxLCJpYXQiOjE3MDUzMTkwMjEsImp0aSI6IjM3YzNlYzhmYzljMDQwN2ZiMzk3NzhiOWEyN2EyYWYwIiwidXNlcl9pZCI6MX0.67vk5j6rRPzKbWShVPImxNgp0lFIt4q3AReKykG8Q2w

{
    "image_url":"https://www.lindadress.com/content/res/large/l93/0009330_wedding_dresses_wm.jpeg", 
    "face_url":"https://www.lindadress.com/content/res/large/l93/0009335_cocktail_dress_wm.jpeg"
}


### Watermark api call