# Generated by Django 5.0.1 on 2024-01-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(default='', max_length=255)),
                ('face_url', models.URLField(default='', max_length=255)),
                ('result_url', models.URLField(blank=True, null=True)),
                ('result_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('mask_image_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
